apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: faulty-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/non-existent/repo.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

